[theme]
primaryColor = "#0077B5"  # LinkedIn Blue
backgroundColor = "#fff7ed"  # Muted orange
secondaryBackgroundColor = "#f8f8f7"  # Muted gray for cards
textColor = "#0a0a0a"  # Deep black
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
